// Downloads every public source into data/raw/. Safe to re-run; overwrites files.
import { mkdir, writeFile } from 'node:fs/promises';

const RAW = new URL('../data/raw/', import.meta.url);
await mkdir(RAW, { recursive: true });

const API = 'https://iptv-org.github.io/api/';
const SOURCES = [
  // iptv-org JSON API (superset of the M3U playlists, includes UA/Referer requirements and labels)
  ...['channels', 'feeds', 'streams', 'logos', 'categories', 'countries', 'languages', 'regions', 'subdivisions', 'blocklist', 'guides']
    .map(n => ({ name: `iptv-org.${n}.json`, url: `${API}${n}.json` })),
  // iptv-org M3U (kept for reference / diffing against the API)
  { name: 'iptv-org.index.m3u', url: 'https://iptv-org.github.io/iptv/index.m3u' },
  { name: 'iptv-org.al.m3u', url: 'https://iptv-org.github.io/iptv/countries/al.m3u' },
  { name: 'iptv-org.xk.m3u', url: 'https://iptv-org.github.io/iptv/countries/xk.m3u' },
  { name: 'iptv-org.mk.m3u', url: 'https://iptv-org.github.io/iptv/countries/mk.m3u' },
  { name: 'iptv-org.sqi.m3u', url: 'https://iptv-org.github.io/iptv/languages/sqi.m3u' },
  // Free-TV curated playlist
  { name: 'free-tv.playlist.m3u8', url: 'https://raw.githubusercontent.com/Free-TV/IPTV/master/playlist.m3u8' },
  { name: 'free-tv.albania.m3u8', url: 'https://raw.githubusercontent.com/Free-TV/IPTV/master/playlists/playlist_albania.m3u8' },
  { name: 'free-tv.epglist.txt', url: 'https://raw.githubusercontent.com/Free-TV/IPTV/master/epglist.txt' },
  // FAST services (Pluto TV, Samsung TV Plus, Roku, Tubi) as generated by BuddyChewChew/app-m3u-generator (Plex omitted: needs token)
  ...['plutotv_all', 'samsungtvplus_all', 'roku_all', 'tubi_all'].map(n => ({ name: `fast.${n}.m3u`, url: `https://raw.githubusercontent.com/BuddyChewChew/app-m3u-generator/main/playlists/${n}.m3u` })),
  // Albanian EPG (XMLTV, gzipped) from epgshare01
  { name: 'epgshare01.AL1.xml.gz', url: 'https://epgshare01.online/epgshare01/epg_ripper_AL1.xml.gz', binary: true },
  { name: 'epgshare01.AL1.channels.txt', url: 'https://epgshare01.online/epgshare01/epg_ripper_AL1.txt' },
];

const started = Date.now();
let ok = 0, failed = 0;
await Promise.all(SOURCES.map(async s => {
  const t0 = Date.now();
  try {
    const res = await fetch(s.url, { signal: AbortSignal.timeout(120_000), headers: { 'user-agent': 'iptv-myapp/0.1 (personal research)' } });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const buf = Buffer.from(await res.arrayBuffer());
    await writeFile(new URL(s.name, RAW), buf);
    ok++;
    console.log(`ok   ${s.name.padEnd(32)} ${(buf.length / 1024).toFixed(0).padStart(7)} KB  ${Date.now() - t0} ms`);
  } catch (e) {
    failed++;
    console.log(`FAIL ${s.name.padEnd(32)} ${e.message}`);
  }
}));
// Gjirafa live-channel API (Kosovo/Albanian broadcasters' official player backend)
try {
  const { fetchGjirafaLive } = await import('./gjirafa.mjs');
  const list = await fetchGjirafaLive();
  await writeFile(new URL('gjirafa.json', RAW), JSON.stringify(list, null, 1));
  ok++; console.log(`ok   ${'gjirafa.json'.padEnd(32)} ${String(list.length).padStart(7)} live items`);
} catch (e) { failed++; console.log(`FAIL gjirafa.json  ${e.message}`); }

// Rakuten TV free live channels for the Albania market
try {
  const { fetchRakutenChannels } = await import('./rakuten.mjs');
  const list = await fetchRakutenChannels();
  await writeFile(new URL('rakuten.json', RAW), JSON.stringify(list, null, 1));
  ok++; console.log(`ok   ${'rakuten.json'.padEnd(32)} ${String(list.length).padStart(7)} live channels`);
} catch (e) { failed++; console.log(`FAIL rakuten.json  ${e.message}`); }

// Local DVB-T2 tuner on the LAN (optional; sources/local-tuner.json)
try {
  const { fetchTunerChannels } = await import('./tuner.mjs');
  const list = await fetchTunerChannels();
  if (list) { await writeFile(new URL('tuner.json', RAW), JSON.stringify(list, null, 1)); ok++; console.log(`ok   ${'tuner.json'.padEnd(32)} ${String(list.length).padStart(7)} over-the-air channels`); }
} catch (e) { failed++; console.log(`FAIL tuner.json  ${e.message}`); }

console.log(`\n${ok} downloaded, ${failed} failed, ${((Date.now() - started) / 1000).toFixed(1)}s`);
if (failed) process.exitCode = 1;
